### PR TITLE
Fix Dependencies

### PR DESCRIPTION
**Pull request by shemnon**
re-apply #37

Signed-off-by: Danno Ferrin <danno.ferrin@gmail.com>

### CODE REVIEW

**Comment by shemnon** [comment]
fixes hyperledger/besu#1651

**Comment by ajsutton** [comment]
If I remember correctly, the `updateBesu.sh` script completely overwrites the `besu.rb` on update so you may need to apply the change to its template too.

**Comment by shemnon** [comment]
Yea, looks like the template was causing the regression.

**Review by ajsutton — APPROVED** [review]
LGTM.

**Pull request merged**
